server:
  port: 8081

datasource:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

file:
  storage: ${FILE_STORAGE}
  aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}

spring:
  batch:
    job:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
